const crypto = require("crypto");
const pool = require("./postgres");
const config = require("../config/config");
const { immediateEmailPercentage, immediateEmailPastWindowMs, futureEmailWindowMs } = config.seed;
const MAILBOXES = config.mailBoxes;
const MAILBOX_MIN_HOURLY_LIMIT = config.minHourlyLimit;
const MAILBOX_MAX_HOURLY_LIMIT = config.maxHourlyLimit;
const CAMPAIGNS = config.campaigns;
const EMAILS = config.emails;
const BATCH_SIZE = config.emailBatchSize;
const GLOBAL_RATE_LIMIT_CAPACITY = config.globalRateLimitCapacity;
const GLOBAL_RATE_LIMIT_INITIAL_TOKENS = config.globalRateLimitInitialTokens;
const GLOBAL_RATE_LIMIT_REFILL_RATE = config.globalRateLimitRefillRate;

async function seed() {
    console.log("Seeding database...");
    const { rows } = await pool.query(
        "SELECT COUNT(*) count FROM scheduled_emails"
    );

    if (Number(rows[0].count) > 0) {
        console.log("Database already seeded.");
        return;
    }

    const client = await pool.connect();
    try {
        await client.query("BEGIN");
        console.log("Creating mailboxes...");
        const mailboxValues = [];
        const mailboxPlaceholders = [];
        let param = 1;
        for (let i = 1; i <= MAILBOXES; i++) {
            mailboxPlaceholders.push(`($${param++}, $${param++})`);
            mailboxValues.push(`mailbox${i}@example.com`, MAILBOX_MIN_HOURLY_LIMIT + Math.floor(Math.random() * (MAILBOX_MAX_HOURLY_LIMIT - MAILBOX_MIN_HOURLY_LIMIT + 1)));
        }

        await client.query(
            `
            INSERT INTO mailboxes(
                email_address,
                hourly_limit
            )
            VALUES
            ${mailboxPlaceholders.join(",")}
            ON CONFLICT(email_address)
            DO NOTHING
            `,
            mailboxValues
        );

        await client.query(
            `
            INSERT INTO global_rate_limiter (
                id,
                capacity,
                tokens,
                refill_rate,
                last_refill_at
            )
            VALUES (
                1,
                $1,
                $2,
                $3,
                NOW()
            )
            ON CONFLICT (id)
            DO UPDATE
            SET
                capacity = EXCLUDED.capacity,
                tokens = EXCLUDED.tokens,
                refill_rate = EXCLUDED.refill_rate,
                last_refill_at = NOW();
            `,
            [
                GLOBAL_RATE_LIMIT_CAPACITY,
                GLOBAL_RATE_LIMIT_INITIAL_TOKENS,
                GLOBAL_RATE_LIMIT_REFILL_RATE,
            ]
        );

        const { rows: mailboxRows } = await client.query(
            `
                SELECT id
                FROM mailboxes
                ORDER BY id
                `
        );

        const mailboxIds = mailboxRows.map(row => row.id);
        console.log("Creating scheduled emails...");
        for (let start = 0; start < EMAILS; start += BATCH_SIZE) {
            const placeholders = [];
            const values = [];
            let index = 1;
            const end = Math.min(start + BATCH_SIZE, EMAILS);
            for (let i = start; i < end; i++) {
                const mailboxId = mailboxIds[Math.floor(Math.random() * mailboxIds.length)];
                const campaignId = Math.floor(Math.random() * CAMPAIGNS) + 1;
                const scheduledAt = Math.random() < immediateEmailPercentage ? new Date(Date.now() - Math.random() * immediateEmailPastWindowMs) :
                    new Date(Date.now() + Math.random() * futureEmailWindowMs);

                placeholders.push(`
                (
                    $${index++},
                    $${index++},
                    $${index++},
                    $${index++},
                    $${index++},
                    $${index++},
                    'pending',
                    0,
                    $${index++},
                    NOW(),
                    NOW()
                )
                `);

                values.push(campaignId, mailboxId, `user${i}@gmail.com`, `Campaign ${campaignId} - Email ${i}`, `Hello User ${i},This is a test email generated by the seed script.Regards,Smartlead`, scheduledAt, crypto.randomUUID());
            }

            await client.query(
                `
                INSERT INTO scheduled_emails(
                    campaign_id,
                    mailbox_id,
                    to_address,
                    subject,
                    body,
                    scheduled_at,
                    status,
                    attempts,
                    idempotency_key,
                    created_at,
                    updated_at
                )
                VALUES
                ${placeholders.join(",")}
                `,
                values
            );
            console.log(`Inserted ${end}/${EMAILS} emails`);
        }
        await client.query("COMMIT");
        console.log("Database seeded successfully.");
    } catch (err) {
        await client.query("ROLLBACK");
        throw err;
    } finally {
        client.release();
    }
}

module.exports = seed;